// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtyhUqVwrUTX0524SUbvvPQ6en2jE_tTU',
    appId: '1:882911627438:web:7b2b482443c4ba6332853f',
    messagingSenderId: '882911627438',
    projectId: 'login-57730',
    authDomain: 'login-57730.firebaseapp.com',
    storageBucket: 'login-57730.appspot.com',
    measurementId: 'G-0P1XLQE8XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdvLLp_FCz3KGnJAzt16dml5GERoM4_wY',
    appId: '1:882911627438:android:be9b8f7cdc02099532853f',
    messagingSenderId: '882911627438',
    projectId: 'login-57730',
    storageBucket: 'login-57730.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_ODMeNDeHvDdsDGoueb-ExU0yZs8f614',
    appId: '1:882911627438:ios:822bb3a23aecc7f032853f',
    messagingSenderId: '882911627438',
    projectId: 'login-57730',
    storageBucket: 'login-57730.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_ODMeNDeHvDdsDGoueb-ExU0yZs8f614',
    appId: '1:882911627438:ios:822bb3a23aecc7f032853f',
    messagingSenderId: '882911627438',
    projectId: 'login-57730',
    storageBucket: 'login-57730.appspot.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtyhUqVwrUTX0524SUbvvPQ6en2jE_tTU',
    appId: '1:882911627438:web:a6293e8a8c4f56c832853f',
    messagingSenderId: '882911627438',
    projectId: 'login-57730',
    authDomain: 'login-57730.firebaseapp.com',
    storageBucket: 'login-57730.appspot.com',
    measurementId: 'G-K61E42GSRB',
  );

}